CREATE TABLE IF NOT EXISTS client
(
    ID   INT          NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL CHECK ( CHAR_LENGTH(NAME) >= 3 AND CHAR_LENGTH(NAME) <= 200 ),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS planet
(
    ID   VARCHAR(500) NOT NULL,
    NAME VARCHAR(500) NOT NULL CHECK ( CHAR_LENGTH(NAME) >= 1 AND CHAR_LENGTH(NAME) <= 500 ),
    PRIMARY KEY (ID)
);

CREATE TRIGGER UPPERCASE_INSERT BEFORE INSERT ON planet FOR EACH ROW
    SET NEW.ID = UPPER(NEW.ID);

CREATE TRIGGER UPPERCASE_UPDATE BEFORE UPDATE ON planet FOR EACH ROW
    SET NEW.ID = UPPER(NEW.ID);

CREATE TABLE IF NOT EXISTS ticket
(
    ID       INT           NOT NULL AUTO_INCREMENT,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CLIENT_ID   INT,
    FROM_PLANET_ID VARCHAR(500),
    TO_PLANET_ID VARCHAR(500),
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FROM_PLANET_ID) REFERENCES planet(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (TO_PLANET_ID) REFERENCES planet(ID) ON DELETE CASCADE ON UPDATE CASCADE
);